name: Go

on:
  push:
    branches: [ "bo/dflybsd-port" ]
  pull_request:
    branches: [ "bo/dflybsd-port" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build (Linux)
      run: |
        go build -v -o wireguard-go-linux

    - name: Build (DragonFly)
      run: |
        GOOS=dragonfly GOARCH=amd64 go build -v -o wireguard-go-dragonfly

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: wireguard-go-build
        path: |
          wireguard-go-linux
          wireguard-go-dragonfly
