name: Go

on:
  push:
    branches: [ "bo/dflybsd-port" ]
  pull_request:
    branches: [ "bo/dflybsd-port" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Show structure (debug)
      run: |
        ls -R
        find . -name go.mod

    - name: Build (Linux)
      run: |
        cd cmd/wireguard-go
        go build -v -o wireguard-go-linux

    - name: Build (DragonFly)
      run: |
        cd cmd/wireguard-go
        GOOS=dragonfly GOARCH=amd64 go build -v -o wireguard-go-dragonfly

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: wireguard-go-build
        path: |
          cmd/wireguard-go/wireguard-go-linux
          cmd/wireguard-go/wireguard-go-dragonfly
